###
GET http://localhost:5000/api/users/all HTTP/1.1

###
POST http://localhost:5000/api/users/register HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@example.com",
    "password": "12345678",
    "address": "Quito",
    "phone": "0326598745"
}

###
DELETE http://localhost:5000/api/products/delete/1 HTTP/1.1

###
POST  http://localhost:5000/api/products/update/1 HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "slug": "",
    "category": "",
    "description": "",
    "price": 0,
    "image": ""
}